DROP table IF EXISTS `sse_fjy_security_info`;

CREATE TABLE `sse_fjy_security_info` (
                                         `id` bigint NOT NULL AUTO_INCREMENT COMMENT '非交易基础信息ID',
                                         `ref_data_type` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '参考数据类型',
                                         `no_trade_security_id` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '非交易证券代码',
                                         `no_trade_security_name` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '非交易证券名称',
                                         `product_security_id` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品证券代码',
                                         `product_security_name` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品证券名称',
                                         `no_trade_busi_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '非交易业务类型',
                                         `no_trade_order_input_startdate` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '非交易订单输入开始日期',
                                         `no_trade_order_input_enddate` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '非交易订单输入结束日期',
                                         `no_trade_whole_num` bigint DEFAULT NULL COMMENT '非交易订单整手数',
                                         `no_trade_min_order` bigint DEFAULT NULL COMMENT '非交易订单最小订单数量',
                                         `no_trade_max_order` bigint DEFAULT NULL COMMENT '非交易订单的最大订单数量',
                                         `no_trade_price` double DEFAULT NULL COMMENT '非交易价格',
                                         `ipo_whole_quantity` bigint DEFAULT NULL COMMENT 'IPO总量',
                                         `ipo_distr_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'IPO分配方法',
                                         `ipo_offer_date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'IPO竞价分配或比例配售日期',
                                         `ipo_check_date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'IPO验资或配号日期',
                                         `ipo_lottery_date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'IPO摇号抽签的日期',
                                         `ipo_apply_price_floor` double DEFAULT NULL COMMENT 'IPO申购价格区间下限',
                                         `ipo_apply_price_ceil` double DEFAULT NULL COMMENT 'IPO申购价格区间上限',
                                         `ipo_match_scale` double DEFAULT NULL COMMENT 'IPO比例配售比例',
                                         `match_regist_date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '配股股权登记日',
                                         `match_execute_date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '配股除权日',
                                         `match_security_scale` double DEFAULT NULL COMMENT '配股比例',
                                         `match_security_whole_value` bigint DEFAULT NULL COMMENT '配股总量',
                                         `t2_value` double DEFAULT NULL COMMENT 'T-2 日基金收益/基金净值',
                                         `t1_value` double DEFAULT NULL COMMENT 'T-1 日基金收益/基金净值',
                                         `offer_type` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发行方式',
                                         `remark` varchar(46) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
                                         PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品非交易基础信息表';